# Generated by Django 5.1.3 on 2024-11-25 11:44

from django.db import migrations
from django.utils.timezone import now

def add_emotion_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Emotion = apps.get_model('emotions', 'Emotion')
    user = User.objects.first()
    if not user:
        user = User.objects.create_user(username='testuser', password='password123')

    Emotion.objects.create(
        user=user,
        emotion_type="happiness",
        intensity=80,
        content="I felt great today!",
        timestamp=now()
    )

class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_alter_emotion_timestamp'),
    ]


    operations = [
        migrations.RunPython(add_emotion_data),
    ]