# Generated by Django 5.1.3 on 2024-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_add_initial_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='burned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('burned', 'Burned'), ('planet', 'Planet')], default='active', max_length=10),
        ),
    ]
