# Generated by Django 5.1.3 on 2024-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_emotion_burned_at_emotion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emotion',
            name='input_mode',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='intensity',
            field=models.IntegerField(),
        ),
    ]
