# Generated by Django 5.1.3 on 2024-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0005_rename_content_emotion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
